import type { Founder, FounderStory, ScoreMetric } from "./types";

export const featuredFounders: Founder[] = [
  {
    id: "fahad-al-rashid",
    name: "Fahad Al-Rashid",
    initials: "FA",
    avatarColor: "bg-primary",
    title: "CEO & Co-founder",
    company: "PayFlow Arabia",
    sector: "FinTech",
    stage: "Series A",
    location: "Riyadh",
    founderScore: 92,
    tags: ["Open to Invest", "B2B Expert", "Offering Mentorship"],
    bio: "Building the next generation of payment infrastructure for Saudi Arabia and the GCC. Previously led product at a major regional bank.",
    joinedDate: "2024-01-15",
    featured: true,
  },
  {
    id: "noura-al-dosari",
    name: "Noura Al-Dosari",
    initials: "NA",
    avatarColor: "bg-secondary",
    title: "Founder & CEO",
    company: "MedConnect MENA",
    sector: "HealthTech",
    stage: "Seed",
    location: "Jeddah",
    founderScore: 88,
    tags: ["Seeking Partnerships", "Hiring Engineers", "Marketplace Builder"],
    bio: "Connecting patients with specialists across the region through AI-powered telemedicine. Former physician turned entrepreneur.",
    joinedDate: "2024-02-20",
    featured: true,
  },
  {
    id: "omar-al-khatib",
    name: "Omar Al-Khatib",
    initials: "OA",
    avatarColor: "bg-accent",
    title: "CTO & Co-founder",
    company: "Noor AI Labs",
    sector: "AI/ML",
    stage: "Series A",
    location: "Dubai",
    founderScore: 91,
    tags: ["Offering Mentorship", "B2B Expert", "Seeking Partnerships"],
    bio: "Developing Arabic-first large language models for enterprise applications. PhD in computational linguistics from MIT.",
    joinedDate: "2024-01-28",
    featured: true,
  },
];

export const directoryFounders: Founder[] = [
  {
    id: "salman-al-harbi",
    name: "Salman Al-Harbi",
    initials: "SA",
    avatarColor: "bg-primary",
    title: "Founder",
    company: "Taelum Academy",
    sector: "EdTech",
    stage: "Pre-Seed",
    location: "Riyadh",
    founderScore: 74,
    tags: ["Seeking CTO", "Looking for Co-founder"],
    bio: "Creating personalized learning paths for K-12 students in Saudi Arabia with adaptive AI technology.",
    joinedDate: "2024-06-10",
  },
  {
    id: "lama-al-qahtani",
    name: "Lama Al-Qahtani",
    initials: "LA",
    avatarColor: "bg-secondary",
    title: "CEO & Co-founder",
    company: "Manzil Technologies",
    sector: "PropTech",
    stage: "Seed",
    location: "Riyadh",
    founderScore: 81,
    tags: ["Marketplace Builder", "Hiring Engineers"],
    bio: "Revolutionizing the Saudi real estate experience with data-driven property matching and virtual tours.",
    joinedDate: "2024-04-05",
  },
  {
    id: "khalid-al-mansour",
    name: "Khalid Al-Mansour",
    initials: "KA",
    avatarColor: "bg-accent",
    title: "Founder & CEO",
    company: "Shams Energy",
    sector: "CleanTech",
    stage: "Series B",
    location: "Jeddah",
    founderScore: 85,
    tags: ["Open to Invest", "Offering Mentorship"],
    bio: "Leading the transition to solar microgrids for commercial buildings across the Kingdom.",
    joinedDate: "2024-02-14",
  },
  {
    id: "reem-al-saud",
    name: "Reem Al-Saud",
    initials: "RA",
    avatarColor: "bg-primary",
    title: "Founder",
    company: "Souq Studios",
    sector: "E-commerce",
    stage: "Seed",
    location: "Riyadh",
    founderScore: 79,
    tags: ["Marketplace Builder", "Seeking Partnerships"],
    bio: "Empowering Saudi artisans and small brands to reach global markets through a curated marketplace.",
    joinedDate: "2024-05-22",
  },
  {
    id: "tariq-al-farsi",
    name: "Tariq Al-Farsi",
    initials: "TA",
    avatarColor: "bg-secondary",
    title: "CEO",
    company: "Wasl Logistics",
    sector: "Logistics",
    stage: "Pre-Seed",
    location: "Doha",
    founderScore: 68,
    tags: ["Looking for Co-founder", "Seeking CTO"],
    bio: "Building last-mile delivery infrastructure optimized for the Gulf region's unique climate and geography.",
    joinedDate: "2024-08-01",
  },
  {
    id: "huda-al-balushi",
    name: "Huda Al-Balushi",
    initials: "HA",
    avatarColor: "bg-accent",
    title: "Founder & CEO",
    company: "Matbakh Cloud",
    sector: "FoodTech",
    stage: "Seed",
    location: "Manama",
    founderScore: 76,
    tags: ["Hiring Engineers", "B2B Expert"],
    bio: "Operating cloud kitchens that bring diverse cuisines to underserved neighborhoods across Bahrain and Saudi Arabia.",
    joinedDate: "2024-07-15",
  },
  {
    id: "youssef-al-mahmoud",
    name: "Youssef Al-Mahmoud",
    initials: "YA",
    avatarColor: "bg-primary",
    title: "CTO & Co-founder",
    company: "Rakeen SaaS",
    sector: "SaaS",
    stage: "Series A",
    location: "Abu Dhabi",
    founderScore: 83,
    tags: ["B2B Expert", "Offering Mentorship"],
    bio: "Providing enterprise resource planning tools tailored for SMEs in the Middle East and North Africa.",
    joinedDate: "2024-03-10",
  },
  {
    id: "sara-al-otaibi",
    name: "Sara Al-Otaibi",
    initials: "SO",
    avatarColor: "bg-secondary",
    title: "Founder",
    company: "Riyali",
    sector: "FinTech",
    stage: "Pre-Seed",
    location: "Riyadh",
    founderScore: 71,
    tags: ["Seeking CTO", "Looking for Co-founder"],
    bio: "Designing financial literacy and micro-savings tools for young Saudi professionals.",
    joinedDate: "2024-09-02",
  },
  {
    id: "abdulrahman-al-ghamdi",
    name: "Abdulrahman Al-Ghamdi",
    initials: "AG",
    avatarColor: "bg-accent",
    title: "Founder & CTO",
    company: "Basira Analytics",
    sector: "AI/ML",
    stage: "Seed",
    location: "Jeddah",
    founderScore: 77,
    tags: ["Hiring Engineers", "Seeking Partnerships"],
    bio: "Using computer vision and AI to automate quality control in Saudi manufacturing plants.",
    joinedDate: "2024-06-28",
  },
  {
    id: "maha-al-shamsi",
    name: "Maha Al-Shamsi",
    initials: "MA",
    avatarColor: "bg-primary",
    title: "CEO & Co-founder",
    company: "Elm Academy",
    sector: "EdTech",
    stage: "Seed",
    location: "Dubai",
    founderScore: 80,
    tags: ["Offering Mentorship", "Marketplace Builder"],
    bio: "Building an online platform connecting tutors and students across the GCC for personalized education.",
    joinedDate: "2024-04-18",
  },
  {
    id: "faisal-al-tamimi",
    name: "Faisal Al-Tamimi",
    initials: "FT",
    avatarColor: "bg-secondary",
    title: "Founder & CEO",
    company: "Aqar Plus",
    sector: "PropTech",
    stage: "Series A",
    location: "Riyadh",
    founderScore: 86,
    tags: ["Open to Invest", "B2B Expert"],
    bio: "Digitizing commercial real estate transactions in Saudi Arabia with blockchain-backed smart contracts.",
    joinedDate: "2024-03-25",
  },
  {
    id: "dalal-al-kuwaiti",
    name: "Dalal Al-Kuwaiti",
    initials: "DA",
    avatarColor: "bg-accent",
    title: "Founder",
    company: "Sahha Clinic",
    sector: "HealthTech",
    stage: "Pre-Seed",
    location: "Kuwait City",
    founderScore: 69,
    tags: ["Seeking CTO", "Looking for Co-founder"],
    bio: "Developing a mental health platform that provides culturally sensitive therapy for Arabic speakers.",
    joinedDate: "2024-09-10",
  },
  {
    id: "nasser-al-subaie",
    name: "Nasser Al-Subaie",
    initials: "NS",
    avatarColor: "bg-primary",
    title: "CEO",
    company: "Tawseel Express",
    sector: "Logistics",
    stage: "Seed",
    location: "Riyadh",
    founderScore: 73,
    tags: ["Hiring Engineers", "Seeking Partnerships"],
    bio: "Creating same-day B2B delivery networks connecting Saudi warehouses with retail partners.",
    joinedDate: "2024-08-20",
  },
  {
    id: "aisha-al-hajri",
    name: "Aisha Al-Hajri",
    initials: "AH",
    avatarColor: "bg-secondary",
    title: "Founder & CEO",
    company: "Akhdar Solutions",
    sector: "CleanTech",
    stage: "Pre-Seed",
    location: "Abu Dhabi",
    founderScore: 67,
    tags: ["Looking for Co-founder", "Seeking Partnerships"],
    bio: "Developing water recycling systems for residential compounds in the UAE and Saudi Arabia.",
    joinedDate: "2024-10-01",
  },
  {
    id: "hamad-al-dosari",
    name: "Hamad Al-Dosari",
    initials: "HD",
    avatarColor: "bg-accent",
    title: "CEO & Co-founder",
    company: "Daleel Market",
    sector: "E-commerce",
    stage: "Series A",
    location: "Riyadh",
    founderScore: 84,
    tags: ["Marketplace Builder", "Open to Invest"],
    bio: "Building the leading B2B wholesale marketplace for Saudi retailers and suppliers.",
    joinedDate: "2024-03-15",
  },
];

export const allFounders: Founder[] = [...featuredFounders, ...directoryFounders];

/** Placeholder testimonials — replace with real quotes once approved. */
export const founderStories: FounderStory[] = [
  {
    id: "story-1",
    quote:
      "[Placeholder] Joining Wosool connected me with founders who truly understand the challenges of scaling in the GCC. The peer mentorship alone has been invaluable to our growth journey.",
    founderName: "Fahad Al-Rashid",
    company: "PayFlow Arabia",
    initials: "FA",
    avatarColor: "bg-primary",
  },
  {
    id: "story-2",
    quote:
      "[Placeholder] Through Wosool, I found my technical co-founder and two of our earliest angel investors. The community is genuinely invested in each other's success.",
    founderName: "Noura Al-Dosari",
    company: "MedConnect MENA",
    initials: "NA",
    avatarColor: "bg-secondary",
  },
  {
    id: "story-3",
    quote:
      "[Placeholder] The Founder Score gave me a clear roadmap of what to improve. Within six months of acting on the feedback, we closed our Series A. Wosool is more than a network — it's an accelerator for your mindset.",
    founderName: "Omar Al-Khatib",
    company: "Noor AI Labs",
    initials: "OA",
    avatarColor: "bg-accent",
  },
];

export const scoreMetrics: ScoreMetric[] = [
  {
    name: "Traction",
    description:
      "Revenue growth, user acquisition, and key milestones achieved over time.",
    icon: "TrendingUp",
  },
  {
    name: "Team",
    description:
      "Strength and completeness of the founding team, key hires, and advisory board.",
    icon: "Users",
  },
  {
    name: "Market",
    description:
      "Market size, competitive positioning, and alignment with regional opportunities.",
    icon: "Target",
  },
  {
    name: "Network",
    description:
      "Depth of connections, partnerships, and engagement within the Wosool community.",
    icon: "Network",
  },
  {
    name: "Execution",
    description:
      "Speed and quality of shipping product, iterating on feedback, and hitting targets.",
    icon: "Zap",
  },
  {
    name: "Engagement",
    description:
      "Active participation in events, mentorship circles, and peer group sessions.",
    icon: "Activity",
  },
];

/** Founders who joined in the last 3 months (new members). */
export const newMembers: Founder[] = directoryFounders.filter((f) =>
  [
    "sara-al-otaibi",
    "tariq-al-farsi",
    "nasser-al-subaie",
    "dalal-al-kuwaiti",
    "aisha-al-hajri",
    "huda-al-balushi",
  ].includes(f.id),
);
