import type { Company, SectorInfo } from "./types";

export const companies: Company[] = [
  // Featured companies
  {
    id: "naqla",
    name: "Naqla",
    initial: "N",
    brandColor: "#2563EB",
    sector: "Logistics",
    stage: "Series A",
    founderName: "Omar Al-Khatib",
    description: "AI-powered last-mile delivery platform optimizing routes across Saudi cities.",
    keyMetric: "50K+ Users",
    tags: ["AI", "Last-Mile", "Delivery"],
    featured: true,
    hiring: true,
    hiringRoles: 5,
  },
  {
    id: "sahha",
    name: "Sahha",
    initial: "S",
    brandColor: "#059669",
    sector: "HealthTech",
    stage: "Seed",
    founderName: "Noura Al-Dosari",
    description: "Digital health records platform connecting clinics across the GCC.",
    keyMetric: "200+ Clinics",
    tags: ["Digital Health", "EHR", "GCC"],
    featured: true,
    openForCollaboration: true,
  },
  {
    id: "riyali",
    name: "Riyali",
    initial: "R",
    brandColor: "#C8A951",
    sector: "FinTech",
    stage: "Series A",
    founderName: "Fahad Al-Rashid",
    description: "Shariah-compliant digital payments for businesses and consumers.",
    keyMetric: "$2M+ Processed",
    tags: ["Payments", "Shariah", "B2B"],
    featured: true,
    hiring: true,
    hiringRoles: 3,
  },
  // Rising companies
  {
    id: "tadreeb",
    name: "Tadreeb",
    initial: "T",
    brandColor: "#7C3AED",
    sector: "EdTech",
    stage: "Pre-Seed",
    founderName: "Salman Al-Harbi",
    description: "Vocational training marketplace for Saudi youth entering the workforce.",
    keyMetric: "5K+ Students",
    tags: ["Training", "Youth", "Marketplace"],
    rising: true,
    openForCollaboration: true,
    fundraising: true,
    fundingRound: "Pre-Seed",
    fundingTarget: "$500K",
  },
  {
    id: "manzil",
    name: "Manzil",
    initial: "M",
    brandColor: "#EA580C",
    sector: "PropTech",
    stage: "Seed",
    founderName: "Lama Al-Qahtani",
    description: "Smart rental platform with AI-powered property matching in Riyadh.",
    keyMetric: "1K+ Listings",
    tags: ["Rental", "AI Matching", "Riyadh"],
    rising: true,
    fundraising: true,
    fundingRound: "Seed",
    fundingTarget: "$1.5M",
  },
  {
    id: "tabkha",
    name: "Tabkha",
    initial: "T",
    brandColor: "#DC2626",
    sector: "FoodTech",
    stage: "Pre-Seed",
    founderName: "Huda Al-Balushi",
    description: "Cloud kitchen platform connecting home chefs with local customers.",
    keyMetric: "3K+ Orders",
    tags: ["Cloud Kitchen", "Home Chefs", "Local"],
    rising: true,
    fundraising: true,
    fundingRound: "Pre-Seed",
    fundingTarget: "$750K",
  },
  // Recently updated companies
  {
    id: "shamsi-energy",
    name: "Shamsi Energy",
    initial: "S",
    brandColor: "#F59E0B",
    sector: "CleanTech",
    stage: "Series A",
    founderName: "Khalid Al-Mutairi",
    description: "Solar energy solutions for commercial properties across Saudi Arabia.",
    keyMetric: "150+ Installations",
    tags: ["Solar", "Commercial", "Green Energy"],
    openForCollaboration: true,
    lastUpdated: "2 days ago",
    updateNote: "Expanded to UAE market",
  },
  {
    id: "souq-digital",
    name: "Souq Digital",
    initial: "S",
    brandColor: "#0891B2",
    sector: "E-commerce",
    stage: "Seed",
    founderName: "Reem Al-Zahrani",
    description: "Artisan marketplace connecting Saudi craftsmen with global buyers.",
    keyMetric: "800+ Artisans",
    tags: ["Artisan", "Marketplace", "Global"],
    openForCollaboration: true,
    lastUpdated: "1 week ago",
    updateNote: "Launched new seller dashboard",
  },
  {
    id: "cloudsync-arabia",
    name: "CloudSync Arabia",
    initial: "C",
    brandColor: "#4F46E5",
    sector: "SaaS",
    stage: "Series A",
    founderName: "Ahmad Al-Subaie",
    description: "Enterprise cloud infrastructure tailored for MENA compliance standards.",
    keyMetric: "50+ Enterprise Clients",
    tags: ["Cloud", "Enterprise", "Compliance"],
    hiring: true,
    hiringRoles: 4,
    lastUpdated: "3 days ago",
    updateNote: "Launched new API platform",
  },
  {
    id: "mawrid-ai",
    name: "Mawrid AI",
    initial: "M",
    brandColor: "#9333EA",
    sector: "AI/ML",
    stage: "Seed",
    founderName: "Sara Al-Ghamdi",
    description: "Arabic NLP tools for businesses to analyze customer sentiment.",
    keyMetric: "10M+ Queries",
    tags: ["NLP", "Arabic", "Sentiment"],
    lastUpdated: "5 days ago",
    updateNote: "Released Arabic GPT integration",
  },
  // Additional companies for sector diversity
  {
    id: "darb-fintech",
    name: "Darb",
    initial: "D",
    brandColor: "#0D9488",
    sector: "FinTech",
    stage: "Seed",
    founderName: "Youssef Al-Otaibi",
    description: "BNPL solution designed for the Saudi retail market.",
    keyMetric: "20K+ Transactions",
    tags: ["BNPL", "Retail", "Payments"],
  },
  {
    id: "shifaa",
    name: "Shifaa",
    initial: "S",
    brandColor: "#16A34A",
    sector: "HealthTech",
    stage: "Pre-Seed",
    founderName: "Maha Al-Shammari",
    description: "Telemedicine platform for rural communities in Saudi Arabia.",
    keyMetric: "2K+ Consultations",
    tags: ["Telemedicine", "Rural", "Access"],
  },
  {
    id: "bina",
    name: "Bina",
    initial: "B",
    brandColor: "#B45309",
    sector: "PropTech",
    stage: "Series A",
    founderName: "Majed Al-Harthy",
    description: "Construction management SaaS for mega-projects in the Gulf.",
    keyMetric: "30+ Projects",
    tags: ["Construction", "SaaS", "Mega-Projects"],
  },
  {
    id: "fekra-ai",
    name: "Fekra AI",
    initial: "F",
    brandColor: "#6D28D9",
    sector: "AI/ML",
    stage: "Pre-Seed",
    founderName: "Aisha Al-Dosari",
    description: "AI-powered market research tool for MENA startups.",
    keyMetric: "500+ Reports",
    tags: ["Market Research", "AI", "MENA"],
  },
  {
    id: "wasel",
    name: "Wasel",
    initial: "W",
    brandColor: "#1D4ED8",
    sector: "Logistics",
    stage: "Seed",
    founderName: "Tariq Al-Omari",
    description: "Fleet management and route optimization for SME logistics.",
    keyMetric: "300+ Fleets",
    tags: ["Fleet", "Optimization", "SME"],
  },
  {
    id: "elm-academy",
    name: "Elm Academy",
    initial: "E",
    brandColor: "#7E22CE",
    sector: "EdTech",
    stage: "Seed",
    founderName: "Nada Al-Harbi",
    description: "Coding bootcamp platform with job placement guarantee.",
    keyMetric: "1.2K+ Graduates",
    tags: ["Coding", "Bootcamp", "Jobs"],
  },
  {
    id: "matjar",
    name: "Matjar",
    initial: "M",
    brandColor: "#0E7490",
    sector: "E-commerce",
    stage: "Series A",
    founderName: "Hassan Al-Jaber",
    description: "Social commerce tools for Saudi Instagram and TikTok sellers.",
    keyMetric: "15K+ Sellers",
    tags: ["Social Commerce", "Instagram", "TikTok"],
  },
  {
    id: "qudra",
    name: "Qudra",
    initial: "Q",
    brandColor: "#CA8A04",
    sector: "CleanTech",
    stage: "Seed",
    founderName: "Badr Al-Dosari",
    description: "Smart water management systems for Saudi agriculture.",
    keyMetric: "40+ Farms",
    tags: ["Water", "Agriculture", "IoT"],
  },
  {
    id: "tawseel",
    name: "Tawseel",
    initial: "T",
    brandColor: "#2563EB",
    sector: "Logistics",
    stage: "Pre-Seed",
    founderName: "Faisal Al-Qahtani",
    description: "Same-day delivery network for GCC e-commerce brands.",
    keyMetric: "8K+ Deliveries",
    tags: ["Same-Day", "E-commerce", "GCC"],
  },
  {
    id: "seha-plus",
    name: "Seha Plus",
    initial: "S",
    brandColor: "#15803D",
    sector: "HealthTech",
    stage: "Series A",
    founderName: "Lamia Al-Farsi",
    description: "AI-powered diagnostics platform for radiology departments.",
    keyMetric: "100+ Hospitals",
    tags: ["AI Diagnostics", "Radiology", "Hospitals"],
  },
  {
    id: "musheed",
    name: "Musheed",
    initial: "M",
    brandColor: "#0369A1",
    sector: "FinTech",
    stage: "Seed",
    founderName: "Abdulrahman Al-Qahtani",
    description: "Automated accounting and tax compliance for Saudi SMEs.",
    keyMetric: "3K+ Businesses",
    tags: ["Accounting", "Tax", "SME"],
  },
];

export const sectors: SectorInfo[] = [
  { name: "FinTech", icon: "Landmark", companyCount: 12, color: "#C8A951" },
  { name: "HealthTech", icon: "Heart", companyCount: 8, color: "#059669" },
  { name: "EdTech", icon: "GraduationCap", companyCount: 6, color: "#7C3AED" },
  { name: "PropTech", icon: "Building2", companyCount: 5, color: "#EA580C" },
  { name: "AI/ML", icon: "Brain", companyCount: 9, color: "#9333EA" },
  { name: "E-commerce", icon: "ShoppingCart", companyCount: 7, color: "#0891B2" },
  { name: "Logistics", icon: "Truck", companyCount: 4, color: "#2563EB" },
  { name: "CleanTech", icon: "Leaf", companyCount: 3, color: "#F59E0B" },
];

export const featuredCompanies = companies.filter((c) => c.featured);
export const risingCompanies = companies.filter((c) => c.rising);
export const recentlyUpdatedCompanies = companies.filter((c) => c.lastUpdated);
export const collaborationCompanies = companies.filter(
  (c) => c.openForCollaboration
);
export const hiringCompanies = companies.filter((c) => c.hiring);
export const fundraisingCompanies = companies.filter((c) => c.fundraising);
